gen_model:
  model_name: "/content/drive/MyDrive/StudiesAI/RL/PromptCompressor/PromptCompressor_code_RL/gpt2_xl_code_v3_n32/checkpoints/checkpoint_19"
  apply_model_parallel: True
  tokenizer:
    model_name: gpt2-xl-code-finetuned
    padding_side: left
    truncation_side: left
    pad_token_as_eos_token: True
  generation_kwargs:
    do_sample: False
    min_new_tokens: 1
    max_new_tokens: 30

reward_fn:
  id: combine
  args:
    threshold: 0.8
    lamb: -0.05
    rouge_type: bleu

datapool:
  id: code_alpaca
  args:
    path: "sahil2801/CodeAlpaca-20k"
    num_tokens_to_predict: 30

env:
  n_envs: 8
  obs_space: FixedTokenObservation
  act_space: BatchFixedTokenAction
  args:
    max_prompt_length: 512
    max_episode_length: 1
    terminate_on_eos: True

alg:
  id: pg_mask
  args:
    sample_k: 4
    use_scst: true
    n_steps: 1
    gae_lambda: 1
    gamma: 1
    batch_size: 32
    verbose: 0
    learning_rate: 0.00003
    normalize_advantage: false
    ent_coef: 0.005

  policy:
    id: BatchTokenPolicy
    args:
      model_name: distilroberta-base
      lr_scheduler:

train_evaluation:
  eval_batch_size: 32
  n_iters: 20
  save_every: 1
  eval_freq: 100000000 # deprecated
  generation_kwargs:
    do_sample: False
    min_new_tokens: 1
    max_new_tokens: 512